import {
  StyleSheet,
} from 'react-native';
export default{
  main:{
  	flex:1,
  },
  head:{
    backgroundColor:'#66cccc',
    alignItems:'center',
    flexDirection:'row',
    height:45,
  },
  hedTit:{
    color:'#fff',alignSelf:'center',marginLeft:'40%'
  },
  hedBg:{
    width:'100%',height:250,
  },
  loginOrRegistBtn:{
    width:'90%',
    marginLeft:'5%',
    height:45,
    marginTop:10,
    backgroundColor:'#66cccc',
    alignItems:'center',
  },
  btnTxt:{},
  search:{},
  iconBack:{
  	width:14,
  	height:18,
    marginLeft:10,
    marginTop:5
  },
  name:{

  },
  listFooter:{
  	backgroundColor:'#ccc',
  	height:40,
  },
  listFooterTxt:{
  	alignSelf:'center',
  	lineHeight:30
  },
  iconMore:{
    width:10,
    height:18,
    position:'absolute',
    alignSelf:'center',
    right:10
  }
};